### ISSUE TITLE
还是不太明白能细讲吗？

### ISSUE THREAD

**Issue by ghost** [Yangff/node_pcsapi#1]
最后那一步不懂？携带以下信息那后面的不懂，携带的信息哪里看？然后之后又怎么就可以操作网盘了，能讲细一点吗？

**Comment by ghost** [comment]
我想用qt做一个程序，用来自动上传本地的文件到百度网盘，怎么做呢？

**Comment by Yangff** [comment]
..这个api大概是用不了了 
你可以试试 https://github.com/houtianze/bypy 这玩意吧。。

**Comment by Yangff** [comment]
另外我并没有做上传的功能…… 这里的上传只是为了用来秒下离线文件的。。

**Comment by ghost** [comment]
谢谢，我想通过抓包来实现，因为qt里有自带浏览器，post方法到http，不知道能否可行，在试中

**Comment by Yangff** [comment]
@wojiaojiao 可以的。

**Comment by ghost** [comment]
我想获取http的json数据，响应的json没显示在http网页上，用火狐浏览器可以得到响应的JSON，但是qt好像只能得到显示在http网页上的json数据，怎么解决？

**Comment by ghost** [comment]
我想用qt做一个自动上传本地文件到百度云的功能
我是用火狐浏览器抓包的，当点击百度网盘的上传按钮，会出现post方法，然后会返回JSON响应。
用到post和get，但是不知道怎么get到网页返回的json,因为返回的json不直接到html页面上。
post方法也不会用，
反正折腾了好久是搞不定post文件到服务器，也get不到json响应
望指导

**Comment by Yangff** [comment]
@wojiaojiao 直接用qt里拿到的cookie构造个上传包发过去就行了，反正你对qt-webkit里的运行环境有控制权。
